# Generated by Django 3.1.4 on 2023-07-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.CharField(max_length=200),
        ),
    ]
